### ISSUE TITLE
library (signal) in ttgranier module

### ISSUE THREAD

**Issue by LucaBelelli** [EnricoTomelleri/ttalkR#3]
ttalkR users may find convenient to run ttscrape and save locally the resulting mydta_xx matrixes for later analysis with the different routines (e.g ttgranier) . However the library (signal) is called in ttscrape only, while if using directly my data_xx as argument of ttgranier produces an error (Error in savitzkyGolay(ts, 0, 1, 11) ).  The "tt signal" library should be called also at the beginning of ttgranier to let this routine work independently.

**Comment by EnricoTomelleri** [comment]
Thank you Luca! Now the signal library is loaded directly in ttgranier(). Cheers, Enrico
